name: MyPlayground
on:
  workflow_dispatch:
jobs:
  firstJob:
    name: first-job
    runs-on: ubuntu-latest
    steps:
      - name: Set up env
        run: |
          echo "Running the first job of this workflow"
          echo "env=my-env" >> "$GITHUB_ENV"
      - name: Displaying env
        run: |
          echo "env value: ${{env.env}}"
        
      
